### ISSUE TITLE
Push Notification Convenience 

### ISSUE THREAD

**Issue by LlamaPlays** [Flieh/diplicity-beta-feedback#18]
When I recieve a push notification, I click on it and when it comes to press, I can't see anything else. If I back button usually to check the board, I go out the app. I suggest allowing players to back button to the board.

**Comment by zond** [comment]
https://developer.android.com/training/implementing-navigation/temporal.html#SynthesizeBackStack

**Comment by zond** [comment]
See https://github.com/zond/android-diplicity/issues/44

**Comment by zond** [comment]
Fixed in https://github.com/zond/android-diplicity/commit/4592e1f5d6a9d6d5f9d4f556bc53619c8e40b69d
